### PR TITLE
v4

### LINKED ISSUE #111: Optionally make startup jobs run early
**Is your feature request related to a problem? Please describe.**
When hosted in an aspnet.core app, some tasks may require to be done before the server is even ready to accepts requests (cache warming up, tire-kicking internal healthchecks, ...).

Currently, by default, the startup jobs seems to be triggered alongside Kestrel.

Given the following

```csharp
using NCronJob;
using NCronJob.TestProgram;

var webApp = WebApplication.CreateBuilder();

webApp.Services.AddNCronJob(s => s.AddJob<TestJob>().RunAtStartup());

await using var run = webApp.Build();

run.MapGet("/", () => string.Empty);
await run.RunAsync();

public partial class Program;

....

public class TestJob : IJob
{
    public async Task RunAsync(IJobExecutionContext context, CancellationToken token){

        Console.WriteLine("** Here begins the startup job");
        await Task.Delay(TimeSpan.FromSeconds(10));
        Console.WriteLine("** Here ends the startup job");
    }
}
```

Here's the output
```text
** Here begins the startup job
warn: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[8]
      The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:60258
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:60259
info: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider[1]
      No action descriptors found. This may indicate an incorrectly configured application or missing application parts. To learn more, visit https://aka.ms/aspnet/mvc/app-parts
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\Code\NCronJob\tests\NCronJob.TestProgram
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:60258/ - - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: GET /'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:60258/ - 200 - text/plain;+charset=utf-8 89.9289ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:60258/favicon.ico - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:60258/favicon.ico - 499 - - 2.7169ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET https://localhost:60258/favicon.ico, Response status code: 499
** Here ends the startup job
```

**Describe the solution you'd like**
Maybe an optional parameter to `RunAtStartup()`?
The requirement would be to ensure those jobs are finished before Kestrel spins up.

Wouldn't this be easy to make this auto-magically happen, I'd be fine with something like

```csharp
run.MapGet("/", () => string.Empty);

await run.Services.GetRequiredService<IStartupJobsRunner>().GoBaby();

await run.RunAsync();
```

### PR DESCRIPTION
**Pull request by linkdotnet**
This PR will hold all new features for `v4`. When merged to `main` - we will release it to the wild.
Preview release have to be released from this branch!

### Additional (All the features/changes for v4)
This PR includes:
 * #111 
 * #122 
 * #126 
 * #128 
 * #136

### CODE REVIEW

**Comment by nulltoken** [comment]
@linkdotnet What's the plan to reintroduce v3 changes into this branch?

**Comment by linkdotnet** [comment]
I will rebase the v4 with the current master - so we will have all the changes. 
if there are too many things going on on v4 maybe I’ll switch to merge instead of rebase

**Comment by nulltoken** [comment]
> I will rebase the v4 with the current master - so we will have all the changes.
> if there are too many things going on on v4 maybe I’ll switch to merge instead of rebase

Thx. That'd be helpful. I have started a WIP on the "detection of ambiguous jobDefinitions" (portions of #108 discussion with a v4 target in mind) and I need some portions of #124 (v3) to progress further.

**Comment by linkdotnet** [comment]
> > I will rebase the v4 with the current master - so we will have all the changes.
> > if there are too many things going on on v4 maybe I’ll switch to merge instead of rebase
> 
> Thx. That'd be helpful. I have started a WIP on the "detection of ambiguous jobDefinitions" (portions of #108 discussion with a v4 target in mind) and I need some portions of #124 (v3) to progress further.

I will rebase `main` after your 2 PR's are merged and hopefully my open one as well :D

**Comment by nulltoken** [comment]
> and hopefully my open one as well :D

Yep, I'd also need this one for the ambiguous detection WIP.

**Comment by linkdotnet** [comment]
@nulltoken Rebase done

**Comment by nulltoken** [comment]
> EDIT 2: That said, your changes should go live, I assume? Therefore I would make a new release.

I'd love to be able to benefit from #132 before v4 ;-)

**Comment by nulltoken** [comment]
>EDIT: We can also probably "freeze" v3. So that we don't develop any more features. Only if there is a really urgent bugfix, I would argue we should tackle. Otherwise we make our lives harder :D

Deal.

**Pull request merged**
