### PR TITLE
Publish code coverage results

### PR DESCRIPTION
**Pull request by nulltoken**
## Pull request description
This is an attempt at starting to surface the code coverage of NCronJob with every change.

### PR meta checklist
- [x] Pull request is targeted at `main` branch for code   
- [ ] Pull request is linked to all related issues, if any.

### Code PR specific checklist
- [ ] My code follows the code style of this project and AspNetCore coding guidelines.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] I have updated the appropriate sub section in the _CHANGELOG.md_.
- [ ] I have added, updated or removed tests to according to my changes.
  - [ ] All tests passed.

### CODE REVIEW

**Comment by nulltoken** [comment]
@linkdotnet As of now, the result is attached to the summary of the Action (see https://github.com/NCronJob-Dev/NCronJob/actions/runs/11611424212 for instance).

Few issues at the moment:
- Coverage is different depending on the platform. I suspect this is related to source generators but have no real clue what to do with that.
  - Options:
    - Quick and dirty: Pick a platform among the matrix where the %coverage makes sense. Elect it to solely be in charge of running the reporting through a conditional GH action
    - Hard: Get a better understanding why this happens and have it fixed
- Having the coverage in the action brings some value, but require some manual clicking to dig at it. One option would be to submit it as a PR comment. But I can't test that from a fork.
  - Proposal: Put this topic on hold for now and potentially let you move it forward (as you've got the proper rights to test this out)
  - Potential drawback: Each matrix execution will try and update the comment. I don't know how that's going to behave. Will 3 comments be generated? Will only one (my current guess) be created/updated?

**Comment by linkdotnet** [comment]
Hey @nulltoken 

Thanks for the proposal. Here my two cents:

Probably it would make sense to make the coverage a different run, that only runs once our test pipeline is passing. We can basically **always** use Ubuntu as host OS to have a nice baseline. Our test-suite doesn't run very long, so I am fine with duplicated runs.

That might solve some issue. another dimension might be multiple target frameworks. Not sure, how they play into that.
There are free OSS services like Codecov that can post comments like your proposal.

**Comment by linkdotnet** [comment]
Nice approach! That also works

**Comment by nulltoken** [comment]
Ok. I get something that works. And generates a coverage report.

image

See https://coveralls.io/jobs/155361408 for latest report

See also https://coveralls.io/github/NCronJob-Dev/NCronJob

Note: I didn't have to create a coveralls account for this to work.

**Comment by nulltoken** [comment]
Hmmm... For some reason, although the reporting works, diving through the files doesn't work as expected (See: https://coveralls.io/builds/70646012/source?filename=src%2FNCronJob%2FConfiguration%2FDynamicJobFactory.cs)

I don't know why. I know there are limits to what can be done in the context of a PR from a forked repository, But the repo being public, I don't understand why coveralls refuses to show the source code....

**Comment by nulltoken** [comment]
Oh! I got it

image

https://coveralls.io/github/NCronJob-Dev/NCronJob/settings

I believe you'll have to click on the button yourself ;-)

**Comment by linkdotnet** [comment]
> Oh! I got it
> 
> image
> 
> https://coveralls.io/github/NCronJob-Dev/NCronJob/settings
> 
> I believe you'll have to click on the button yourself ;-)

Not sure what to expect - I did :D

**Comment by linkdotnet** [comment]
If you want we can merge that and see what happens :D

**Comment by linkdotnet** [comment]
Also feel free to add your contributins to the `CHANGELOG.md`

**Comment by nulltoken** [comment]
>> I believe you'll have to click on the button yourself ;-)

> Not sure what to expect - I did :D

Strange. When refreshing the page, the "CLAIM" button is still active...

**Comment by nulltoken** [comment]
> If you want we can merge that and see what happens :D

Let's do that. This kind of things usually takes a couple of attempts to be set up properly.

**Review by linkdotnet — APPROVED** [review]

**Comment by linkdotnet** [comment]
Let's do it

**Comment by nulltoken** [comment]
So....

Good news:
- The publish on merge worked.
- There's a shiny new 85% badge that the lib could showcase on the README
- There's now an easy way to check if all major files are covered enough

Less good news:
- Still no source code
- The repo at coveralls still claims it isn't owned yet, even in "incognito" navigation mode (Which may explain the "no source code yet")

Maybe that thing runs in an async way. I'll check back tomorrow.

**Comment by nulltoken** [comment]
> * The repo at coveralls still claims it isn't owned yet, even in "incognito" navigation mode (Which may explain the "no source code yet")

@linkdotnet Still is the case. Silly question, once you've claimed the repository, did you hit the big "Save changes" button at the bottom of the page?

**Comment by linkdotnet** [comment]
Maybe not :D 

Now I did

**Comment by nulltoken** [comment]
> Maybe not :D
> 
> Now I did

Hmmm. Things are still a bit blurry from what I see. When you log in on coveralls, do you see NCronJob as your repo?

BTW, have you seen this? https://coveralls.io/new-github-integration-beta

**Comment by linkdotnet** [comment]
Interesting - currently I am more in favor of switching over to either SonarCloud or Codecov. Both had less problems in my experience

**Comment by nulltoken** [comment]
> Interesting - currently I am more in favor of switching over to either SonarCloud or Codecov. Both had less problems in my experience

As the owner, could you,please take care of CodeCov first steps (account creation, granting rights and secret token setup)?

https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage

**Pull request merged**
