### PR TITLE
v3 branch

### PR DESCRIPTION
**Pull request by linkdotnet**
This is the ongoing branch for `v3`.

### CODE REVIEW

**Comment by linkdotnet** [comment]
Fixes #44 
Fixes #59

**Comment by falvarez1** [comment]
@linkdotnet what do you think about converting `Task` to `ValueTask` for `IJob.RunAsync`? Since this already creates breaking changes to IJob if changing to ValueTask improves performance then it can be included. Of course, I would need to run some benchmarks before making any changes.

**Review by falvarez1 — APPROVED** [review]

**Comment by linkdotnet** [comment]
> @linkdotnet what do you think about converting `Task` to `ValueTask` for `IJob.RunAsync`? Since this already creates breaking changes to IJob if changing to ValueTask improves performance then it can be included. Of course, I would need to run some benchmarks before making any changes.

That is a good idea - I didn't have very much time lately but those smaller things seemed somewhat in reach without investing hours in one session (what one would need for bigger features).

Coming back - `ValueTask` might be a good choice here as well. Absolutely.

**Comment by linkdotnet** [comment]
I will create a ticket for that.

**Pull request merged**
